apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalgapi-deployment
  labels:
    app: catalgapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalgapi
  template:
    metadata:
      labels:
        app: catalgapi
    spec:
      containers:
        - name: catalgapi
          image: pbshoppingacr.azurecr.io/catalogapi:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: '64Mi'
              cpu: '0.1'
            limits:
              memory: '128Mi'
              cpu: '0.3'
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalgapi-service
spec:
  selector:
    app: catalgapi
  ports:
    - protocol: TCP
      port: 80
